### ISSUE TITLE
Recurring connect error

### ISSUE THREAD

**Issue by monkybrain** [smallwins/slack#27]
Sometimes I get the error 

`"Parameter 'url' must be a string, not " + typeof url`

when trying to start the rtm client but not all the time. Can't seem to figure out why. Anyone had this problem?

Stack trace:

```
TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:73:11)
    at Object.urlParse [as parse] (url.js:67:5)
    at WebSocket.initAsClient (/home/philip/Projects/Bots/wherebot/node_modules/ws/lib/WebSocket.js:572:23)
    at new WebSocket (/home/philip/Projects/Bots/wherebot/node_modules/ws/lib/WebSocket.js:78:18)
    at /home/philip/Projects/Bots/wherebot/node_modules/slack/methods/rtm.client.js:48:16
    at Request._callback (/home/philip/Projects/Bots/wherebot/node_modules/slack/methods/_exec.js:36:7)
    at Request.self.callback (/home/philip/Projects/Bots/wherebot/node_modules/request/request.js:200:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/home/philip/Projects/Bots/wherebot/node_modules/request/request.js:1041:10)
```

**Comment by brianleroux** [comment]
the system works! oddly the url param is not always defined so the code crashes loudly (which is good for the library but not for the userland code calling it!) 

where does that url come from?

**Comment by gunar** [comment]
Same here. This happens when there's some problem connecting to slack servers i.e. I can reproduce it by disconnecting my machine from the internet and trying to start the RTM.

**Comment by gunar** [comment]
This throw when `data` is null here: https://github.com/smallwins/slack/blob/master/src/rtm.client.js#L31

**Comment by brianleroux** [comment]
Good call! I just pushed a fix that makes fail states very explicit. Thx!

**Comment by gunar** [comment]
Sorry to bother, but this is still throwing an uncaughtException and crashing node. We should catch that `throw` somewhere, right?

**Comment by brianleroux** [comment]
not a bother! so the only way that throws is if you forgot to pass a token in… or if that token is bad I guess that would bubble the error from slack

is this what you're seeing?

**Comment by gunar** [comment]
I think you forgot to upload the image you wanted. Here's what I see:

![image](https://cloud.githubusercontent.com/assets/7684574/15128911/db8ac79c-1614-11e6-91a4-74a7e8e46fc9.png)

It says `Cleaning up before exit` because I have an `process.on('unhandledException', cleanexit)`.

**Comment by brianleroux** [comment]
so there's no data.url…which comes back from a successful rtm.start call (which *only* requires a valid token)

so if you pass a bad token we fail. seems like an ok error…no?

**Comment by gunar** [comment]
yeahmm... I'm pretty sure my token is valid.

What happens is, in my dev env, this fails intermittently. I guess slack servers deny connections every now and then b/c I'm restarting the connection too often.

I would like to be able to listen to this and restart the connection i.e. without crashing the server.

**Comment by brianleroux** [comment]
So, from my perspective, the library is working 'as advertised' and if Slack responds with an Error we throw. If you want to catch startup errors and add retry logic in your client implementation that would be up to your client. (LMK if that sounds right to you!)

**Comment by gunar** [comment]
Sounds good to me. Where would I catch that error and prevent it from crashing my process?

**Comment by brianleroux** [comment]
Something like this would do the trick:

```
try {
  bot.listen(params)
} catch(e) {
  retryLogicHere() // usually has things like exponential backoff and max tries
}
```

**Comment by gunar** [comment]
Hey, I thought it wouldn't work but tried it anyway. Doesn't work.

Why? I'm pretty sure you can't try/catch async :/

**Comment by brianleroux** [comment]
it'll work if you are just using es5. are you transpiling w/ async/await?

**Comment by gunar** [comment]
I'm running on Node v6 without any transpiling. By 'async' I meant using [try/catch on asynchronous functions](http://stackoverflow.com/questions/3677783/is-it-possible-to-catch-exceptions-thrown-in-a-javascript-async-callback). Am I getting something terribly wrong here?

**Comment by brianleroux** [comment]
Oh! Shit. No, def not you, that is correct functions are asynchronous, however `bot.listen` is synchronous BUT it encapsulates an async call which indeed cannot be `try/catch`ed! (So, my bad.)

Question is, does this warrant a callback for `listen` so I can bubble errors for control. 

Maybe something like ?

```javascript
var slack = require('slack')
var bot = slack.rtm.client()

bot.listen({token:'foo'}, function(err, startupPayload) {
  if (err) {
    // handle retry here
  }
  else {
    // meh!
  }
})
```

**Comment by gunar** [comment]
Habemus papam! Cool, thanks!

Yup, sounds reasonable. So we'll call the callback with the error instead of throwing.

**Comment by brianleroux** [comment]
cool, just pushed `7.1.0` with this 

here's the test: 
https://github.com/smallwins/slack/blob/master/test/00-rtm.client-test.js#L33-L42

seems to work but I'll leave this open for you to confirm it works for you =)

**Comment by gunar** [comment]
Thanks! Not quite yet solved, I fear.

![image](https://cloud.githubusercontent.com/assets/7684574/15164468/5a20b7bc-16e5-11e6-8725-12ccfc8cbdae.png)

`data` is invalid, so `data.url` throws [here](https://github.com/smallwins/slack/blob/master/src/rtm.client.js#L36).

 :bug: :gun:

**Comment by brianleroux** [comment]
hmm, ok this is weird, can you log the rest of `data` so I can see what the rest of the payload says?

**Comment by gunar** [comment]
It's a string LOL

```js
console.log('data is', data)
```
![image](https://cloud.githubusercontent.com/assets/7684574/15191489/4f34824c-178b-11e6-9ce8-951cb835f074.png)

FYI, this happens to me because I use nodemon in my dev environment. I'm not trying to DDoS Slack's API or whatever :innocent:

**Comment by brianleroux** [comment]
Ok! The plot thickens. We *should* be getting a JSON response according to https://api.slack.com/docs/rate-limits (but we are not!) so I pinged Slack. Depending on the answer of the 'right way' I'll push a fix that traps a rate limit error and bubbles it correctly!

**Comment by gunar** [comment]
> If you go over these limits when using our Real Time Messaging API you will receive an error message as a reply. If you continue to send messages your application will be disconnected.

**Comment by brianleroux** [comment]
OK! I've pushed a fix and chatted w/ the good folk at Slack about getting a better error condition in a future API release. LMK if this works for you!

**Comment by gunar** [comment]
That does it, @brianleroux. Thank you so much! :smiley:

**Comment by brianleroux** [comment]
💥  ![bum-wiggle](https://cloud.githubusercontent.com/assets/990/15225558/c7ef0f9c-1833-11e6-8660-519e1ca93b5a.gif)

thx for sticking w/ me in figuring this one out!
